suggestio/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('suggestions/', include('suggestions.urls')),
    path('admin/', admin.site.urls),
]

suggestions/urls.py
from django.urls import path

from . import views

app_name = 'suggestions'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:suggestion_id>/vote/', views.vote, name='vote'),
    path('<int:suggestion_id>/comment/', views.comment, name='comment'),
    path('new/', views.new_suggestion, name='new'),
    path('reset/', views.resetExample, name='reset'),
]

suggestions/models.py
from django.db import models
from datetime import datetime


class Suggestion(models.Model):
    suggestion_title = models.CharField(max_length=50)
    suggestion_text = models.TextField()
    votes = models.IntegerField(default=0)
    submit_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.suggestion_title


class Comment(models.Model):
    suggestion = models.ForeignKey(Suggestion, on_delete=models.CASCADE)
    comment_text = models.TextField()
    submit_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.comment_text

suggestions/forms.py
from django import forms


class SuggestionForm(forms.Form):
    title = forms.CharField(label='Suggestion title', max_length=50)
    text = forms.CharField(widget=forms.Textarea)


class CommentForm(forms.Form):
    # Hidden id input for sending Suggestion foreign key
    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    text = forms.CharField(label='Write a comment', widget=forms.Textarea)

suggestions/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from datetime import date


from .models import Suggestion, Comment
from .forms import SuggestionForm, CommentForm


class IndexView(generic.ListView):
    template_name = 'suggestions/index.html'
    context_object_name = 'latest_suggestion_list'
    model = Suggestion

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            # Could pass more things here.
        })
        return context

    def get_queryset(self):
        return Suggestion.objects.order_by('-votes')


class DetailView(generic.DetailView):
    template_name = 'suggestions/detail.html'
    model = Suggestion

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the comments for the current suggestion
        context['comments'] = Comment.objects.filter(
                suggestion=self.kwargs['pk'])
        # Add the comment form
        context['form'] = CommentForm
        return context


def vote(request, suggestion_id):
    # Get the suggestion object
    suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
    # Increment it's vote value and save the object
    suggestion.votes += 1
    suggestion.save()
    # Finally, redirect back to index page
    return HttpResponseRedirect(
            reverse('suggestions:detail', args=(suggestion.id,)))


def new_suggestion(request):
    # If this is a POST request we need to process the form data
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request:
        form = SuggestionForm(request.POST)
        # Check whether it's valid:
        if form.is_valid():
            # Get the cleaned form data
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            # Create and save the suggestion
            new_suggestion = Suggestion(
                    suggestion_title=title,
                    suggestion_text=text)
            new_suggestion.save()
            # Finally, redirect back to index
            return HttpResponseRedirect(reverse('suggestions:index'))

    # If a GET (or any other method) we'll create a blank form for input
    else:
        form = SuggestionForm()

    return render(request, 'suggestions/new.html', {'form': form})


def comment(request, suggestion_id):
    # If this is a POST request we need to process the form data
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # Check whether it's valid:
        if form.is_valid():
            # Get the submitted comment text and the corresponding suggestion
            text = form.cleaned_data['text']
            suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
            # Create and save the comment
            new_comment = Comment(suggestion=suggestion, comment_text=text)
            new_comment.save()
            # Finally, redirect back to suggestion:
            return HttpResponseRedirect(
                    reverse('suggestions:detail', args=(suggestion.id,)))

    # If GET (or any other method) we'll redirect back to suggestion
    else:
        return HttpResponseRedirect(
                reverse('suggestions:detail', args=(suggestion.id,)))


def resetExample(request):
    # Delete existing data, and populate with example data.
    Suggestion.objects.all().delete()
    s01 = Suggestion(
            suggestion_title="Buy a new coffee brewer to the office",
            suggestion_text="Seriously, we need to talk about this. I "
                            "think we could increase productivity by at "
                            "least 35 percent by buying a new coffee brewer. "
                            "In addition, the employees would be happier. "
                            "Coffee is important, y'all. ",
            votes=47,
            submit_date=date(2017, 12, 29))
    s02 = Suggestion(
            suggestion_title="Have a conference in Italy",
            suggestion_text="We should go to Italy and eat pasta. "
                            "Nothing brings a team together like pasta!",
            votes=1,
            submit_date=date(2018, 1, 22))
    s03 = Suggestion(
            suggestion_title="Get standing desks",
            suggestion_text="You know what they say, sitting kills. We should "
                            "get standing desks so we can work standing up. "
                            "Please vote for #standingdesks2018!",
            votes=18,
            submit_date=date(2018, 2, 7))
    s01.save()
    s02.save()
    s03.save()
    c01 = Comment(
            suggestion_id=s01.id, comment_text="Yes - I'd love this too!")
    c02 = Comment(
            suggestion_id=s01.id, comment_text="This would be awesome <3")
    c03 = Comment(
            suggestion_id=s03.id, comment_text="I'm not sure about this...")
    c01.save()
    c02.save()
    c03.save()
    return HttpResponseRedirect(reverse('suggestions:index'))

suggestions/templates/suggestions/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'suggestions/style.css' %}" />

<body class="l-site">
    <header class="l-site__header">
        <div class="c-header">
            <a class="c-header__logo" href="{% url 'suggestions:index' %}">Suggestio</a>
        </div>
    </header>
    <main class="l-site__content">
        {% block content %}{% endblock %}
    </main>
    <footer class="l__site-footer">
        <div class="c-footer">
            <p class="c-footer__text">Made by Filip Hedberg</p>
        </div>
    </footer>
</body>

suggestions/templates/suggestions/detail.html
{% extends "suggestions/base.html" %}

{% block content %}
<div class="detail-container">
    <div class="top">
        <a class="top__backButton" href="{% url 'suggestions:index' %}">Back</a>
    </div>

    <div class="suggestion">
        <div class="suggestion_metadata">
            <p class="suggestion__date">
                Submitted {{ suggestion.submit_date.date}}
            </p>
        </div>
        <h1 class="suggestion__title">
            {{ suggestion.suggestion_title}}
        </h1>

        <p class="suggestion__text">
            {{ suggestion.suggestion_text}}
        </p>

        <div class="suggestion_actions">
            <div class="suggestion__nrOfVotes">
                {% if suggestion.votes == 1 %}
                    {{ suggestion.votes }} vote
                {% else %}
                    {{ suggestion.votes }} votes
                {% endif %}
            </div>

            <form action="{% url 'suggestions:vote' suggestion.id %}" method="post" id="voteForm">
                {% csrf_token %}
            </form>

            <button class="suggestion_actions__vote-button" type=submit form="voteForm" value="Vote">
                <svg class="ic-thumb ic-thumb--white" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M5 22h-5v-12h5v12zm17.615-8.412c-.857-.115-.578-.734.031-.922.521-.16 1.354-.5 1.354-1.51 0-.672-.5-1.562-2.271-1.49-1.228.05-3.666-.198-4.979-.885.906-3.656.688-8.781-1.688-8.781-1.594 0-1.896 1.807-2.375 3.469-1.221 4.242-3.312 6.017-5.687 6.885v10.878c4.382.701 6.345 2.768 10.505 2.768 3.198 0 4.852-1.735 4.852-2.666 0-.335-.272-.573-.96-.626-.811-.062-.734-.812.031-.953 1.268-.234 1.826-.914 1.826-1.543 0-.529-.396-1.022-1.098-1.181-.837-.189-.664-.757.031-.812 1.133-.09 1.688-.764 1.688-1.41 0-.565-.424-1.109-1.26-1.221z"/></svg>
                Vote on this suggestion
            </button>

        </div>
    </div>

    <div class="comments">
        {% if comments %}
            <p class="comments__numbers">

                {% if comments|length == 1 %}
                    {{ comments|length }} comment:
                {% else %}
                    {{ comments|length }} comments:
                {% endif %}

            </p>

            {% for comment in comments.all %}
            <div class="comment">
                <p class="comment__text">
                    {{ comment.comment_text }}
                </p>
                <p class="comment__date">
                    {{ comment.submit_date }}
                </p>

            </div>

            {% endfor %}

        {% else %}
            <p class="comments__none">No comments</p>
        {% endif %}
    </div>
    <div class="write-comment">
        <form action="{% url 'suggestions:comment' suggestion.id %}" method="post" id="commentForm">
            {% csrf_token %}
            {{ form }}
            <button class="comment-button" type=submit form="commentForm">
                Submit comment
            </button>
        </form>

    </div>
</div>




{% endblock %}

suggestions/templates/suggestions/index.html
{% extends "suggestions/base.html" %}

{% block content %}

<div class="l-index">
    <div class="index-header">
        <header class="index-header__title">
            Suggestions
        </header>

        <form action="{% url 'suggestions:new' %}" id="newForm">
            <button class="index-header__button-new" type=submit form="newForm">
                New suggestion
            </button>
        </form>
    </div>

    {% if latest_suggestion_list %}
        <ul class="suggestion-list">
        {% for suggestion in latest_suggestion_list %}
            <li class="list-item" onclick="location.href = '{% url 'suggestions:detail' suggestion.id %}';">
                <div class="list-item__container">
                    <div class="list-item__suggestion">
                        <div class="list-item__title">
                            {{ suggestion.suggestion_title }}
                        </div>
                        <div class="list-item__text">
                            {{ suggestion.suggestion_text }}
                        </div>
                    </div>
                    <div class="list-item__votes">
                        <div class="list-item__nr-of-votes">
                            {{ suggestion.votes }}
                        </div>
                        <svg class="list-item__thumb ic-thumb ic-thumb--primary" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M5 22h-5v-12h5v12zm17.615-8.412c-.857-.115-.578-.734.031-.922.521-.16 1.354-.5 1.354-1.51 0-.672-.5-1.562-2.271-1.49-1.228.05-3.666-.198-4.979-.885.906-3.656.688-8.781-1.688-8.781-1.594 0-1.896 1.807-2.375 3.469-1.221 4.242-3.312 6.017-5.687 6.885v10.878c4.382.701 6.345 2.768 10.505 2.768 3.198 0 4.852-1.735 4.852-2.666 0-.335-.272-.573-.96-.626-.811-.062-.734-.812.031-.953 1.268-.234 1.826-.914 1.826-1.543 0-.529-.396-1.022-1.098-1.181-.837-.189-.664-.757.031-.812 1.133-.09 1.688-.764 1.688-1.41 0-.565-.424-1.109-1.26-1.221z"/></svg>
                    </div>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No suggestions are available.</p>
    {% endif %}
    <div class="reset-example">
        <a class="reset-example__button-reset" href="{% url 'suggestions:reset' %}">Reset example</a>
    </div>


</div>


{% endblock %}

suggestions/templates/suggestions/new.html
{% extends "suggestions/base.html" %}

{% block content %}

<div class="new-container">
    <header class="new-title">
        New suggestion
    </header>
    <form action="/suggestions/new/" method="post" id="postNewForm">
        {% csrf_token %}
        {{ form.name_of_field.errors }}
        {{ form }}
        <button class="new-button" type=submit form="postNewForm">
            Submit suggestion
        </button>
    </form>
</div>

{% endblock %}